version: '3.9'
services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_PASSWORD: rootadmin
      POSTGRES_USER: postgres
      POSTGRES_DB: contactDetails
  server:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
